### ISSUE TITLE
DataTable, form widget not documented

### ISSUE THREAD

**Issue by xNok** [octobercms/docs#196]
In discover this widget by looking at the [builder plugin](http://octobercms.com/plugin/rainlab-builder) database Table, but the only reference in found is [this old post](https://octobercms.com/forum/post/formwidget-datagrid).

The [backend-forms.md](http://octobercms.com/docs/backend/forms#form-widgets) should document this widget as well as the other formwidgets.

From the first post I think we have the following options

``` yml
items:
    label: items
    type: datagrid
    columns: 
        item:
            title: [..]
            type: [..]
            format: [..]
            options: [..]
```

| Option | Description |
| --- | --- |
| **label** |  |
| **type** |  |
| **columns** |  |

Howerver there is a readme.md in [octobercms table widget folder](https://github.com/octobercms/october/tree/master/modules/backend/widgets/table), It let me think that this widjet as a lot more options.
