### ISSUE TITLE
Documentation for titlefrom (form repeater)

### ISSUE THREAD

**Issue by alpapan** [octobercms/docs#347]
Hello

Could we please have additional documentation (eg. a working example) at https://octobercms.com/docs/backend/forms for the titleFrom option of the Repeater field type?

It took me a while to figure it out but I **think** it only allows type:text fields. The documentation is not clear on how to use this option....

```
extra_information:
    type: repeater
    titleFrom: title_when_collapsed
    form:
        fields:
            added_at:
                label: Date added
                type: datepicker
            details:
                label: Details
                type: textarea
            title_when_collapsed:
                label: This field is the title when collapsed
                type: text
```
thanks!
