### ISSUE TITLE
Form Field Types does not explain how to do checkboxes.

### ISSUE THREAD

**Issue by jbh** [octobercms/docs#39]
The [Form Field Types](http://octobercms.com/docs/backend/forms#form-field-types) documentation does not mention how to do checkboxes.

Here is an example of a checkbox form field:

``` yml
        showFullContent:
            label Show full content?
            type: checkbox
            span: left
            default: true
            comment: This is a comment
            description: This is a description
```
