### ISSUE TITLE
Hard to read and understand the ` available toolbar buttons` blockquote in the section Rich editor / WYSIWYG

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/docs#479]
Maybe it's me as my head is spinning today, but I just look at the blockquote of information found here: https://octobercms.com/docs/backend/forms#widget-richeditor

The blockquote is as follows:

> fullscreen, bold, italic, underline, strikeThrough, subscript, superscript, fontFamily, fontSize, |, color, emoticons, inlineStyle, paragraphStyle, |, paragraphFormat, align, formatOL, formatUL, outdent, indent, quote, insertHR, -, insertLink, insertImage, insertVideo, insertAudio, insertFile, insertTable, undo, redo, clearFormatting, selectAll, html

Then it says:

> Note: | will insert a vertical separator line in the toolbar and - a horizontal one.

All I'm seeing is a wall of text and I kind of have an issue with the `|` and `-` in this wall of text.

Surely it would be better to add some formatting to this wall of text to make it a bit more understandable?

Take this for example as I'm going to second guess what is going on here, the part `fontSize, |, color,` I'm guessing you mean to say `fontSize` can have a `|` and `color` doesn't - who knows?

If there was some proper formatting I couldn't understand it a bit better.

Why it can't be like this?

```
fullscreen, bold, italic, underline, strikeThrough, subscript, superscript, fontFamily, color, emoticons, inlineStyle, paragraphFormat, align, formatOL, formatUL, outdent, indent, quote,insertLink, insertImage, insertVideo, insertAudio, insertFile, insertTable, undo, redo, clearFormatting, selectAll, html

Note: | will insert a vertical separator line in the toolbar and - a horizontal one.

(*) fontSize, paragraphStyle and insertHR ... (Explain more in-depth these three options)
```

My point is this, can it be written for someone who is a complete Newbie and looking at this section for the very first time, be able to understand what is going on - without needing to ask a question. Right now that is not really fulfilling that.

Some second guess examples:

```
html_content:
    type: richeditor
    toolbarButtons: bold|italic|fontSize|8|10|12|fontFamily
    size: huge
```

or

```
html_content:
    type: richeditor
    toolbarButtons: bold|italic|fontSize||fontFamily
    size: huge
```

or
```
html_content:
    type: richeditor
    toolbarButtons: bold|italic|insertHR-
    size: huge
```

etc.
